language: java

jdk:
  - oraclejdk7
  - openjdk7

script:
  - ./gradlew assemble

notifications:
  slack:
      on_success: change
      on_failure: always
      rooms:
        - sqlinantes:ZvBQacDCX5Q116NmXbeZYGZU#team-blockchain
