language: java
jdk:
- oraclejdk7
- openjdk7
script:
- "./gradlew assemble bintrayUpload"
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
    - sqlinantes:8Usex84M6JTsUhBEymvhpm5w#team-blockchain
